version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ${PWD}/config.yml:/app/config.yml
      - ${PWD}/sites.yml:/app/sites.yml
    ports:
      - '1337:1337'
    environment:
      PORT: 1337
